name: request_builder
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  lottie:
  equatable:
  flash: ^3.0.5+1
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true

  assets:
    - assets/json/
