name: request_builder
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  lottie: ^3.2.0
  equatable: ^2.0.7
  flash: ^3.1.1
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/json/
